//! Windows Terminal profile discovery.

const std = @import("std");
const builtin = @import("builtin");
const root = @import("soft_root").root;

const Profile = @import("Profile.zig");

const log = std.log.scoped(.wt_profiles);

pub const Error = error{
    SettingsNotFound,
    BadSettings,
} || std.mem.Allocator.Error || std.Io.File.OpenError || std.Io.File.StatError || std.Io.Reader.Error;

const max_settings_bytes = 8 * 1024 * 1024;

pub fn read(allocator: std.mem.Allocator) Error![]Profile {
    if (builtin.os.tag != .windows) return error.SettingsNotFound;
    const data = try readSettings(allocator);
    defer allocator.free(data);
    return parse(allocator, data);
}

pub fn parse(allocator: std.mem.Allocator, data: []const u8) Error![]Profile {
    const json = try stripComments(allocator, data);
    defer allocator.free(json);

    var parsed = std.json.parseFromSlice(std.json.Value, allocator, json, .{}) catch |e| {
        log.warn("cannot parse Windows Terminal settings: {s}", .{@errorName(e)});
        return error.BadSettings;
    };
    defer parsed.deinit();

    if (parsed.value != .object) return error.BadSettings;
    const settings = parsed.value.object;

    const list = blk: {
        const profiles = settings.get("profiles") orelse return error.BadSettings;
        // "profiles" is usually an object with a "list", but may be the list itself.
        break :blk switch (profiles) {
            .array => |a| a,
            .object => |o| switch (o.get("list") orelse return error.BadSettings) {
                .array => |a| a,
                else => return error.BadSettings,
            },
            else => return error.BadSettings,
        };
    };

    const default_guid = if (settings.get("defaultProfile")) |v| asString(v) else null;

    var result: std.ArrayList(Profile) = .empty;
    errdefer freeList(allocator, &result);

    if (default_guid) |guid| for (list.items) |item| {
        if (!guidEql(item, guid)) continue;
        try append(allocator, &result, item);
        break;
    };

    for (list.items) |item| {
        if (default_guid) |guid| if (guidEql(item, guid)) continue;
        try append(allocator, &result, item);
    }

    return result.toOwnedSlice(allocator);
}

pub const free = Profile.free;

fn append(
    allocator: std.mem.Allocator,
    list: *std.ArrayList(Profile),
    item: std.json.Value,
) std.mem.Allocator.Error!void {
    if (item != .object) return;
    const obj = item.object;

    const name_str = if (obj.get("name")) |v| asString(v) orelse "" else "";

    // Most profiles - including the one people usually default to - are
    // generated by Windows Terminal and carry a "source" instead of a
    // commandline, so those have to be mapped back to something spawnable.
    const raw_command = if (obj.get("commandline")) |v| asString(v) orelse "" else "";
    const command = if (raw_command.len > 0)
        try expandEnvVars(allocator, raw_command)
    else if (obj.get("source")) |v|
        try commandFromSource(allocator, asString(v) orelse "", name_str) orelse return
    else
        return;
    defer allocator.free(command);

    // The command is a spawnable Windows command line (unexpanded).
    var profile = try Profile.dupe(allocator, .{
        .name = if (name_str.len > 0) name_str else command,
        .command = command,
        .icon = iconFor(name_str, command),
    });
    errdefer profile.deinit(allocator);
    try list.append(allocator, profile);
}

/// Best-effort Nerd Font icon guessing.
fn iconFor(name: []const u8, command: []const u8) []const u8 {
    const Entry = struct { []const u8, []const u8 };
    // Ordered most-specific first so e.g. a distro or Visual Studio prompt wins
    // over the generic "linux"/"powershell" fallbacks.
    const entries = [_]Entry{
        // Linux distributions (usually WSL)
        .{ "ubuntu", "\u{f31b}" },
        .{ "debian", "\u{f306}" },
        .{ "archlinux", "\u{f303}" },
        .{ "arch", "\u{f303}" },
        .{ "fedora", "\u{f30a}" },
        .{ "opensuse", "\u{f314}" },
        .{ "suse", "\u{f314}" },
        .{ "alpine", "\u{f300}" },
        .{ "kali", "\u{f327}" },
        .{ "manjaro", "\u{f312}" },
        .{ "linuxmint", "\u{f30e}" },
        .{ "mint", "\u{f30e}" },
        .{ "centos", "\u{f304}" },
        .{ "gentoo", "\u{f30d}" },
        .{ "devuan", "\u{f307}" },
        .{ "nixos", "\u{f313}" },
        .{ "almalinux", "\u{f31d}" },
        .{ "rocky", "\u{f32b}" },
        .{ "raspbian", "\u{f315}" },
        .{ "raspberry", "\u{f315}" },
        .{ "freebsd", "\u{f30c}" },
        .{ "redhat", "\u{f316}" },
        // Visual Studio developer prompts
        .{ "visual studio", "\u{e70c}" },
        .{ "vsdevshell", "\u{e70c}" },
        .{ "developer", "\u{e70c}" },
        // Shells and tools
        .{ "git", "\u{e702}" },
        .{ "powershell", "\u{f0a0a}" },
        .{ "pwsh", "\u{f0a0a}" },
        .{ "command prompt", "\u{ebc4}" },
        .{ "cmd", "\u{ebc4}" },
        .{ "bash", "\u{ebca}" },
        // Generic fallbacks
        .{ "wsl", "\u{f17c}" },
        .{ "linux", "\u{f17c}" },
    };
    for (entries) |entry|
        if (std.ascii.indexOfIgnoreCase(name, entry[0]) != null or
            std.ascii.indexOfIgnoreCase(command, entry[0]) != null)
            return entry[1];
    return "";
}

/// Map a generated profile's "source" back to a command line. Sources that
/// cannot be launched standalone return null and the profile is skipped.
fn commandFromSource(
    allocator: std.mem.Allocator,
    source: []const u8,
    name: []const u8,
) std.mem.Allocator.Error!?[]u8 {
    if (std.mem.eql(u8, source, "Windows.Terminal.PowershellCore"))
        return try resolvePowerShellCore(allocator);

    // WSL distributions are launched by name. The store-installed distros use
    // their own package as the source but launch the same way.
    const is_wsl = std.mem.eql(u8, source, "Windows.Terminal.Wsl") or
        std.mem.eql(u8, source, "Microsoft.WSL") or
        std.mem.startsWith(u8, source, "CanonicalGroupLimited.");
    if (is_wsl and name.len > 0) {
        // Quoted because distro names contain spaces ("Ubuntu 22.04") and this
        // is split again with the Windows command line rules.
        return try std.fmt.allocPrint(allocator, "wsl.exe -d \"{s}\"", .{name});
    }

    return null;
}

/// Locate PowerShell Core the way Windows Terminal does. (yes, this is crazy)
fn resolvePowerShellCore(allocator: std.mem.Allocator) std.mem.Allocator.Error![]u8 {
    if (builtin.os.tag != .windows) return allocator.dupe(u8, "pwsh.exe");

    const env = root.get_init().environ_map;
    const io = root.get_io();

    if (env.get("LOCALAPPDATA")) |local_app_data| {
        const dir_path = try std.fs.path.join(allocator, &.{ local_app_data, "Microsoft\\WindowsApps" });
        defer allocator.free(dir_path);
        if (dirHasEntry(io, dir_path, "pwsh.exe")) {
            const path = try std.fs.path.join(allocator, &.{ dir_path, "pwsh.exe" });
            log.debug("resolved pwsh via the Store alias: {s}", .{path});
            return path;
        }
    }

    for ([_][]const u8{ "ProgramFiles", "ProgramFiles(x86)" }) |var_name| {
        const program_files = env.get(var_name) orelse continue;
        if (try highestPowerShellInstall(allocator, io, program_files)) |path| {
            log.debug("resolved pwsh under {s}: {s}", .{ var_name, path });
            return path;
        }
    }

    log.debug("no pwsh install found, falling back to PATH lookup", .{});
    return allocator.dupe(u8, "pwsh.exe");
}

fn highestPowerShellInstall(
    allocator: std.mem.Allocator,
    io: std.Io,
    program_files: []const u8,
) std.mem.Allocator.Error!?[]u8 {
    const root_path = try std.fs.path.join(allocator, &.{ program_files, "PowerShell" });
    defer allocator.free(root_path);

    var dir = std.Io.Dir.openDirAbsolute(io, root_path, .{ .iterate = true }) catch return null;
    defer dir.close(io);

    var best_version: ?u32 = null;
    var best_path: ?[]u8 = null;
    errdefer if (best_path) |path| allocator.free(path);

    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry| {
        if (entry.kind != .directory) continue;
        const version = std.fmt.parseInt(u32, entry.name, 10) catch continue;
        if (best_version) |best| if (version <= best) continue;

        const install_dir = try std.fs.path.join(allocator, &.{ root_path, entry.name });
        defer allocator.free(install_dir);
        if (!dirHasEntry(io, install_dir, "pwsh.exe")) continue;
        const path = try std.fs.path.join(allocator, &.{ install_dir, "pwsh.exe" });
        if (best_path) |old| allocator.free(old);
        best_version = version;
        best_path = path;
    }

    return best_path;
}

fn dirHasEntry(io: std.Io, dir_path: []const u8, name: []const u8) bool {
    var dir = std.Io.Dir.openDirAbsolute(io, dir_path, .{ .iterate = true }) catch return false;
    defer dir.close(io);
    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry|
        if (std.ascii.eqlIgnoreCase(entry.name, name)) return true;
    return false;
}

/// Replace %VAR% references, which Windows Terminal writes into the static
/// profiles (\"%SystemRoot%\\System32\\cmd.exe\"), with flow expansions.
fn expandEnvVars(allocator: std.mem.Allocator, str: []const u8) std.mem.Allocator.Error![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    var i: usize = 0;
    while (i < str.len) {
        if (str[i] != '%') {
            try out.append(allocator, str[i]);
            i += 1;
            continue;
        }
        const end = std.mem.indexOfScalarPos(u8, str, i + 1, '%') orelse {
            try out.append(allocator, str[i]);
            i += 1;
            continue;
        };
        const name = str[i + 1 .. end];
        if (name.len > 0) {
            try out.appendSlice(allocator, "{{env:");
            try out.appendSlice(allocator, name);
            try out.appendSlice(allocator, "}}");
            i = end + 1;
            continue;
        }
        // Unknown or empty: keep the text verbatim.
        try out.appendSlice(allocator, str[i .. end + 1]);
        i = end + 1;
    }

    return out.toOwnedSlice(allocator);
}

fn freeList(allocator: std.mem.Allocator, list: *std.ArrayList(Profile)) void {
    for (list.items) |*profile| profile.deinit(allocator);
    list.deinit(allocator);
}

fn asString(value: std.json.Value) ?[]const u8 {
    return switch (value) {
        .string, .number_string => |s| s,
        else => null,
    };
}

fn guidEql(item: std.json.Value, guid: []const u8) bool {
    if (item != .object) return false;
    const value = item.object.get("guid") orelse return false;
    const item_guid = asString(value) orelse return false;
    return std.mem.eql(u8, item_guid, guid);
}

fn readSettings(allocator: std.mem.Allocator) Error![]u8 {
    const io = root.get_io();
    const local_app_data = root.get_init().environ_map.get("LOCALAPPDATA") orelse {
        log.info("no LOCALAPPDATA in environment, cannot locate Windows Terminal settings", .{});
        return error.SettingsNotFound;
    };

    // Each release channel keeps settings.json under its own package, and
    // unpackaged installs use a plain directory. Most stable channel first.
    const candidates = [_][]const u8{
        "Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Packages\\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Packages\\Microsoft.WindowsTerminalCanary_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Microsoft\\Windows Terminal\\settings.json",
    };

    for (candidates) |suffix| {
        const path = try std.fs.path.join(allocator, &.{ local_app_data, suffix });
        defer allocator.free(path);

        if (!std.fs.path.isAbsolute(path)) {
            log.debug("skipping non-absolute candidate: {s}", .{path});
            continue;
        }

        const file = std.Io.Dir.openFileAbsolute(io, path, .{ .mode = .read_only }) catch |e| {
            log.debug("no settings at {s}: {s}", .{ path, @errorName(e) });
            continue;
        };
        defer file.close(io);

        const stat = file.stat(io) catch |e| {
            log.debug("cannot stat {s}: {s}", .{ path, @errorName(e) });
            continue;
        };
        if (stat.size > max_settings_bytes) {
            log.warn("ignoring oversized settings file {s} ({d} bytes)", .{ path, stat.size });
            return error.BadSettings;
        }

        log.info("using Windows Terminal settings: {s}", .{path});
        var reader_buf: [4096]u8 = undefined;
        var reader = file.reader(io, &reader_buf);
        return reader.interface.readAlloc(allocator, @intCast(stat.size));
    }

    log.info("no Windows Terminal settings found under {s}", .{local_app_data});
    return error.SettingsNotFound;
}

/// Blank out `//` and `/* */` comments, preserving length so any parse error
/// offset still lines up with the original file. String literals are skipped so
/// a `//` inside a Windows path is left alone.
fn stripComments(allocator: std.mem.Allocator, data: []const u8) std.mem.Allocator.Error![]u8 {
    const out = try allocator.dupe(u8, data);
    var i: usize = 0;
    var in_string = false;
    while (i < out.len) : (i += 1) {
        if (in_string) {
            switch (out[i]) {
                '\\' => i += 1, // skip the escaped byte
                '"' => in_string = false,
                else => {},
            }
            continue;
        }
        switch (out[i]) {
            '"' => in_string = true,
            '/' => {
                if (i + 1 >= out.len) continue;
                switch (out[i + 1]) {
                    '/' => while (i < out.len and out[i] != '\n') : (i += 1) {
                        out[i] = ' ';
                    },
                    '*' => {
                        const end = std.mem.indexOfPos(u8, out, i + 2, "*/") orelse out.len - 2;
                        // Keep newlines so line numbers survive.
                        while (i < end + 2 and i < out.len) : (i += 1) {
                            if (out[i] != '\n') out[i] = ' ';
                        }
                        i -= 1;
                    },
                    else => {},
                }
            },
            else => {},
        }
    }
    return out;
}

test "stripComments leaves strings alone" {
    const src =
        \\{ // trailing
        \\  "path": "C:\\x", /* block */ "url": "a//b"
        \\}
    ;
    const out = try stripComments(std.testing.allocator, src);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "trailing") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "block") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "a//b") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "C:\\\\x") != null);
    try std.testing.expectEqual(src.len, out.len);
}

test "stripComments preserves line count" {
    const src =
        \\{
        \\  /* one
        \\     two */
        \\  "a": 1
        \\}
    ;
    const out = try stripComments(std.testing.allocator, src);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqual(
        std.mem.count(u8, src, "\n"),
        std.mem.count(u8, out, "\n"),
    );
}

// Shaped after a real settings.json: the default is a generated profile with no
// commandline, and the static entries use %VAR%. (A PowershellCore source is
// intentionally not the default here; resolving it is Windows-runtime behavior
// covered by a separate, non-Windows test.)
const test_settings =
    \\{
    \\    "$help": "https://aka.ms/terminal-documentation",
    \\    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    \\    "profiles":
    \\    {
    \\        "list":
    \\        [
    \\            {
    \\                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    \\                "name": "Windows PowerShell",
    \\                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
    \\            },
    \\            {
    \\                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    \\                "name": "Command Prompt",
    \\                "commandline": "%SystemRoot%\\System32\\cmd.exe"
    \\            },
    \\            {
    \\                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    \\                "name": "Azure Cloud Shell",
    \\                "source": "Windows.Terminal.Azure"
    \\            },
    \\            {
    \\                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    \\                "name": "Ubuntu",
    \\                "source": "Windows.Terminal.Wsl"
    \\            },
    \\            {
    \\                "guid": "{d8b03b9c-49cf-58d7-83b7-7e19629d9cc0}",
    \\                "name": "archlinux",
    \\                "source": "Microsoft.WSL"
    \\            },
    \\            {
    \\                "guid": "{de27c996-0580-53f5-a62d-c2fee961383b}",
    \\                "name": "Developer Command Prompt for VS 2022",
    \\                "source": "Windows.Terminal.VisualStudio"
    \\            }
    \\        ]
    \\    }
    \\}
;

test "parse: dynamic default profile resolves and sorts first" {
    const profiles = try parse(std.testing.allocator, test_settings);
    defer free(std.testing.allocator, profiles);

    try std.testing.expect(profiles.len > 0);
    // The default profile (a generated WSL source) resolves and sorts first.
    try std.testing.expectEqualStrings("Ubuntu", profiles[0].name);
    try std.testing.expectEqualStrings("wsl.exe -d \"Ubuntu\"", profiles[0].command);
}

test "parse: %VAR% becomes a flow env expansion" {
    const profiles = try parse(std.testing.allocator, test_settings);
    defer free(std.testing.allocator, profiles);

    for (profiles) |profile| if (std.mem.eql(u8, profile.name, "Command Prompt")) {
        try std.testing.expectEqualStrings("{{env:SystemRoot}}\\System32\\cmd.exe", profile.command);
        return;
    };
    return error.ProfileNotFound;
}

test "parse: wsl profiles launch by distro name" {
    const profiles = try parse(std.testing.allocator, test_settings);
    defer free(std.testing.allocator, profiles);

    var seen_ubuntu = false;
    var seen_arch = false;
    for (profiles) |profile| {
        if (std.mem.eql(u8, profile.name, "Ubuntu")) {
            try std.testing.expectEqualStrings("wsl.exe -d \"Ubuntu\"", profile.command);
            seen_ubuntu = true;
        }
        if (std.mem.eql(u8, profile.name, "archlinux")) {
            try std.testing.expectEqualStrings("wsl.exe -d \"archlinux\"", profile.command);
            seen_arch = true;
        }
    }
    try std.testing.expect(seen_ubuntu and seen_arch);
}

test "parse: unlaunchable sources are skipped" {
    const profiles = try parse(std.testing.allocator, test_settings);
    defer free(std.testing.allocator, profiles);

    for (profiles) |profile| {
        try std.testing.expect(!std.mem.eql(u8, profile.name, "Azure Cloud Shell"));
        try std.testing.expect(std.mem.indexOf(u8, profile.name, "Developer Command Prompt") == null);
    }
}

test "expandEnvVars: %VAR% converts to a flow env expansion" {
    const a = std.testing.allocator;
    const out = try expandEnvVars(a, "%SystemRoot%\\System32\\cmd.exe");
    defer a.free(out);
    try std.testing.expectEqualStrings("{{env:SystemRoot}}\\System32\\cmd.exe", out);
}

test "expandEnvVars: unpaired and empty markers are left alone" {
    const cases = [_][]const u8{ "100%", "a %% b", "%", "no vars here" };
    for (cases) |case| {
        const out = try expandEnvVars(std.testing.allocator, case);
        defer std.testing.allocator.free(out);
        try std.testing.expectEqualStrings(case, out);
    }
}

test "iconFor: matches known profiles and falls back to none" {
    try std.testing.expectEqualStrings("\u{f0a0a}", iconFor("Windows PowerShell", "powershell.exe"));
    try std.testing.expectEqualStrings("\u{ebc4}", iconFor("Command Prompt", "cmd.exe"));
    try std.testing.expectEqualStrings("\u{f31b}", iconFor("Ubuntu", "wsl.exe -d Ubuntu"));
    // A Visual Studio developer prompt wins over the "powershell" keyword.
    try std.testing.expectEqualStrings("\u{e70c}", iconFor("Developer PowerShell for VS 2022", "pwsh.exe"));
    // "git" wins over "bash" for Git Bash.
    try std.testing.expectEqualStrings("\u{e702}", iconFor("Git Bash", "bash.exe"));
    try std.testing.expectEqualStrings("", iconFor("Custom Thing", "myapp.exe"));
}
