//! Windows Terminal profile discovery.
//!
//! Reads the profile list out of Windows Terminal's settings.json so flow can
//! offer the same shells the user already has configured, and default to the
//! one they picked there instead of falling back to cmd.exe.

const std = @import("std");
const builtin = @import("builtin");
const root = @import("soft_root").root;
const command_line = @import("command_line");

const log = std.log.scoped(.wt_profiles);

pub const Profile = struct {
    name: []const u8,
    /// Command line to run. Profiles without one are skipped, so this is
    /// always something that can actually be spawned.
    command: []const u8,
    /// Set on the profile named by "defaultProfile", which is also sorted first.
    is_default: bool,
};

pub const Error = error{
    SettingsNotFound,
    BadSettings,
} || std.mem.Allocator.Error || std.Io.File.OpenError || std.Io.File.StatError || std.Io.Reader.Error;

const max_settings_bytes = 8 * 1024 * 1024;

/// Profiles from Windows Terminal's settings.json, default first, then file
/// order. Free with `free`.
pub fn read(allocator: std.mem.Allocator) Error![]Profile {
    if (builtin.os.tag != .windows) return error.SettingsNotFound;

    const data = try readSettings(allocator);
    defer allocator.free(data);

    return parse(allocator, data, root.get_init().environ_map);
}

/// Parse the contents of a settings.json. `env` supplies %VAR% expansion and
/// only needs a `get(name) ?[]const u8`.
pub fn parse(allocator: std.mem.Allocator, data: []const u8, env: anytype) Error![]Profile {
    // Windows Terminal writes settings.json with comments, which std.json
    // does not accept, so strip them first.
    const json = try stripComments(allocator, data);
    defer allocator.free(json);

    var parsed = std.json.parseFromSlice(std.json.Value, allocator, json, .{}) catch |e| {
        log.warn("cannot parse Windows Terminal settings: {s}", .{@errorName(e)});
        return error.BadSettings;
    };
    defer parsed.deinit();

    if (parsed.value != .object) return error.BadSettings;
    const settings = parsed.value.object;

    const list = blk: {
        const profiles = settings.get("profiles") orelse return error.BadSettings;
        // "profiles" is usually an object with a "list", but may be the list itself.
        break :blk switch (profiles) {
            .array => |a| a,
            .object => |o| switch (o.get("list") orelse return error.BadSettings) {
                .array => |a| a,
                else => return error.BadSettings,
            },
            else => return error.BadSettings,
        };
    };

    const default_guid = if (settings.get("defaultProfile")) |v| asString(v) else null;

    var result: std.ArrayList(Profile) = .empty;
    errdefer freeList(allocator, &result);

    if (default_guid) |guid| for (list.items) |item| {
        if (!guidEql(item, guid)) continue;
        try append(allocator, &result, item, true, env);
        break;
    };

    for (list.items) |item| {
        if (default_guid) |guid| if (guidEql(item, guid)) continue;
        try append(allocator, &result, item, false, env);
    }

    return result.toOwnedSlice(allocator);
}

pub fn free(allocator: std.mem.Allocator, profiles: []const Profile) void {
    for (profiles) |profile| {
        allocator.free(profile.name);
        allocator.free(profile.command);
    }
    allocator.free(profiles);
}

/// Argv of the default profile, or null if it cannot be determined. Caller owns
/// the result; free with `freeArgv`.
pub fn defaultArgv(allocator: std.mem.Allocator) ?[][]const u8 {
    const profiles = read(allocator) catch |e| {
        log.info("no Windows Terminal default profile ({s}), falling back", .{@errorName(e)});
        return null;
    };
    defer free(allocator, profiles);
    for (profiles) |profile| if (profile.is_default) {
        log.info("using Windows Terminal profile '{s}': {s}", .{ profile.name, profile.command });
        return command_line.splitWindows(allocator, profile.command) catch null;
    };
    log.info("Windows Terminal has no usable default profile, falling back", .{});
    return null;
}

pub const freeArgv = command_line.free;

fn append(
    allocator: std.mem.Allocator,
    list: *std.ArrayList(Profile),
    item: std.json.Value,
    is_default: bool,
    env: anytype,
) std.mem.Allocator.Error!void {
    if (item != .object) return;
    const obj = item.object;

    const name_str = if (obj.get("name")) |v| asString(v) orelse "" else "";

    // Most profiles - including the one people usually default to - are
    // generated by Windows Terminal and carry a "source" instead of a
    // commandline, so those have to be mapped back to something spawnable.
    const raw_command = if (obj.get("commandline")) |v| asString(v) orelse "" else "";
    const command = if (raw_command.len > 0)
        try expandEnvVars(allocator, raw_command, env)
    else if (obj.get("source")) |v|
        try commandFromSource(allocator, asString(v) orelse "", name_str, env) orelse return
    else
        return;
    errdefer allocator.free(command);

    const name = try allocator.dupe(u8, if (name_str.len > 0) name_str else command);
    errdefer allocator.free(name);

    try list.append(allocator, .{ .name = name, .command = command, .is_default = is_default });
}

/// Map a generated profile's "source" back to a command line. Sources that
/// cannot be launched standalone return null and the profile is skipped.
fn commandFromSource(
    allocator: std.mem.Allocator,
    source: []const u8,
    name: []const u8,
    env: anytype,
) std.mem.Allocator.Error!?[]u8 {
    if (std.mem.eql(u8, source, "Windows.Terminal.PowershellCore"))
        return try resolvePowerShellCore(allocator, env);

    // WSL distributions are launched by name. The store-installed distros use
    // their own package as the source but launch the same way.
    const is_wsl = std.mem.eql(u8, source, "Windows.Terminal.Wsl") or
        std.mem.eql(u8, source, "Microsoft.WSL") or
        std.mem.startsWith(u8, source, "CanonicalGroupLimited.");
    if (is_wsl and name.len > 0) {
        // Quoted because distro names contain spaces ("Ubuntu 22.04") and this
        // is split again with the Windows command line rules.
        return try std.fmt.allocPrint(allocator, "wsl.exe -d \"{s}\"", .{name});
    }

    return null;
}

/// Locate PowerShell Core the way Windows Terminal does. (yes, this is crazy)
fn resolvePowerShellCore(allocator: std.mem.Allocator, env: anytype) std.mem.Allocator.Error![]u8 {
    if (builtin.os.tag != .windows) return allocator.dupe(u8, "pwsh.exe");

    const io = root.get_io();

    if (env.get("LOCALAPPDATA")) |local_app_data| {
        const dir_path = try std.fs.path.join(allocator, &.{ local_app_data, "Microsoft\\WindowsApps" });
        defer allocator.free(dir_path);
        if (dirHasEntry(io, dir_path, "pwsh.exe")) {
            const path = try std.fs.path.join(allocator, &.{ dir_path, "pwsh.exe" });
            log.debug("resolved pwsh via the Store alias: {s}", .{path});
            return path;
        }
    }

    for ([_][]const u8{ "ProgramFiles", "ProgramFiles(x86)" }) |var_name| {
        const program_files = env.get(var_name) orelse continue;
        if (try highestPowerShellInstall(allocator, io, program_files)) |path| {
            log.debug("resolved pwsh under {s}: {s}", .{ var_name, path });
            return path;
        }
    }

    log.debug("no pwsh install found, falling back to PATH lookup", .{});
    return allocator.dupe(u8, "pwsh.exe");
}

fn highestPowerShellInstall(
    allocator: std.mem.Allocator,
    io: std.Io,
    program_files: []const u8,
) std.mem.Allocator.Error!?[]u8 {
    const root_path = try std.fs.path.join(allocator, &.{ program_files, "PowerShell" });
    defer allocator.free(root_path);

    var dir = std.Io.Dir.openDirAbsolute(io, root_path, .{ .iterate = true }) catch return null;
    defer dir.close(io);

    var best_version: ?u32 = null;
    var best_path: ?[]u8 = null;
    errdefer if (best_path) |path| allocator.free(path);

    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry| {
        if (entry.kind != .directory) continue;
        const version = std.fmt.parseInt(u32, entry.name, 10) catch continue;
        if (best_version) |best| if (version <= best) continue;

        const install_dir = try std.fs.path.join(allocator, &.{ root_path, entry.name });
        defer allocator.free(install_dir);
        if (!dirHasEntry(io, install_dir, "pwsh.exe")) continue;
        const path = try std.fs.path.join(allocator, &.{ install_dir, "pwsh.exe" });
        if (best_path) |old| allocator.free(old);
        best_version = version;
        best_path = path;
    }

    return best_path;
}

fn dirHasEntry(io: std.Io, dir_path: []const u8, name: []const u8) bool {
    var dir = std.Io.Dir.openDirAbsolute(io, dir_path, .{ .iterate = true }) catch return false;
    defer dir.close(io);
    var iter = dir.iterate();
    while (iter.next(io) catch null) |entry|
        if (std.ascii.eqlIgnoreCase(entry.name, name)) return true;
    return false;
}

/// Expand %VAR% references, which Windows Terminal writes into the static
/// profiles (\"%SystemRoot%\\System32\\cmd.exe\"). An undefined variable is left
/// as written, matching what cmd.exe does.
fn expandEnvVars(allocator: std.mem.Allocator, str: []const u8, env: anytype) std.mem.Allocator.Error![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    var i: usize = 0;
    while (i < str.len) {
        if (str[i] != '%') {
            try out.append(allocator, str[i]);
            i += 1;
            continue;
        }
        const end = std.mem.indexOfScalarPos(u8, str, i + 1, '%') orelse {
            try out.append(allocator, str[i]);
            i += 1;
            continue;
        };
        const name = str[i + 1 .. end];
        if (name.len > 0) if (env.get(name)) |value| {
            try out.appendSlice(allocator, value);
            i = end + 1;
            continue;
        };
        // Unknown or empty: keep the text verbatim.
        try out.appendSlice(allocator, str[i .. end + 1]);
        i = end + 1;
    }

    return out.toOwnedSlice(allocator);
}

fn freeList(allocator: std.mem.Allocator, list: *std.ArrayList(Profile)) void {
    for (list.items) |profile| {
        allocator.free(profile.name);
        allocator.free(profile.command);
    }
    list.deinit(allocator);
}

fn asString(value: std.json.Value) ?[]const u8 {
    return switch (value) {
        .string, .number_string => |s| s,
        else => null,
    };
}

fn guidEql(item: std.json.Value, guid: []const u8) bool {
    if (item != .object) return false;
    const value = item.object.get("guid") orelse return false;
    const item_guid = asString(value) orelse return false;
    return std.mem.eql(u8, item_guid, guid);
}

fn readSettings(allocator: std.mem.Allocator) Error![]u8 {
    const io = root.get_io();
    const local_app_data = root.get_init().environ_map.get("LOCALAPPDATA") orelse {
        log.info("no LOCALAPPDATA in environment, cannot locate Windows Terminal settings", .{});
        return error.SettingsNotFound;
    };

    // Each release channel keeps settings.json under its own package, and
    // unpackaged installs use a plain directory. Most stable channel first.
    const candidates = [_][]const u8{
        "Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Packages\\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Packages\\Microsoft.WindowsTerminalCanary_8wekyb3d8bbwe\\LocalState\\settings.json",
        "Microsoft\\Windows Terminal\\settings.json",
    };

    for (candidates) |suffix| {
        const path = try std.fs.path.join(allocator, &.{ local_app_data, suffix });
        defer allocator.free(path);

        if (!std.fs.path.isAbsolute(path)) {
            log.debug("skipping non-absolute candidate: {s}", .{path});
            continue;
        }

        const file = std.Io.Dir.openFileAbsolute(io, path, .{ .mode = .read_only }) catch |e| {
            log.debug("no settings at {s}: {s}", .{ path, @errorName(e) });
            continue;
        };
        defer file.close(io);

        const stat = file.stat(io) catch |e| {
            log.debug("cannot stat {s}: {s}", .{ path, @errorName(e) });
            continue;
        };
        if (stat.size > max_settings_bytes) {
            log.warn("ignoring oversized settings file {s} ({d} bytes)", .{ path, stat.size });
            return error.BadSettings;
        }

        log.info("using Windows Terminal settings: {s}", .{path});
        var reader_buf: [4096]u8 = undefined;
        var reader = file.reader(io, &reader_buf);
        return reader.interface.readAlloc(allocator, @intCast(stat.size));
    }

    log.info("no Windows Terminal settings found under {s}", .{local_app_data});
    return error.SettingsNotFound;
}

/// Blank out `//` and `/* */` comments, preserving length so any parse error
/// offset still lines up with the original file. String literals are skipped so
/// a `//` inside a Windows path is left alone.
fn stripComments(allocator: std.mem.Allocator, data: []const u8) std.mem.Allocator.Error![]u8 {
    const out = try allocator.dupe(u8, data);
    var i: usize = 0;
    var in_string = false;
    while (i < out.len) : (i += 1) {
        if (in_string) {
            switch (out[i]) {
                '\\' => i += 1, // skip the escaped byte
                '"' => in_string = false,
                else => {},
            }
            continue;
        }
        switch (out[i]) {
            '"' => in_string = true,
            '/' => {
                if (i + 1 >= out.len) continue;
                switch (out[i + 1]) {
                    '/' => while (i < out.len and out[i] != '\n') : (i += 1) {
                        out[i] = ' ';
                    },
                    '*' => {
                        const end = std.mem.indexOfPos(u8, out, i + 2, "*/") orelse out.len - 2;
                        // Keep newlines so line numbers survive.
                        while (i < end + 2 and i < out.len) : (i += 1) {
                            if (out[i] != '\n') out[i] = ' ';
                        }
                        i -= 1;
                    },
                    else => {},
                }
            },
            else => {},
        }
    }
    return out;
}

test "stripComments leaves strings alone" {
    const src =
        \\{ // trailing
        \\  "path": "C:\\x", /* block */ "url": "a//b"
        \\}
    ;
    const out = try stripComments(std.testing.allocator, src);
    defer std.testing.allocator.free(out);
    try std.testing.expect(std.mem.indexOf(u8, out, "trailing") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "block") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "a//b") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "C:\\\\x") != null);
    try std.testing.expectEqual(src.len, out.len);
}

test "stripComments preserves line count" {
    const src =
        \\{
        \\  /* one
        \\     two */
        \\  "a": 1
        \\}
    ;
    const out = try stripComments(std.testing.allocator, src);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqual(
        std.mem.count(u8, src, "\n"),
        std.mem.count(u8, out, "\n"),
    );
}

const TestEnv = struct {
    map: std.StaticStringMap([]const u8),
    fn get(self: TestEnv, name: []const u8) ?[]const u8 {
        return self.map.get(name);
    }
};

const test_env: TestEnv = .{ .map = .initComptime(.{
    .{ "SystemRoot", "C:\\Windows" },
}) };

// Shaped after a real settings.json: the default is a generated profile with no
// commandline, and the static entries use %VAR%.
const test_settings =
    \\{
    \\    "$help": "https://aka.ms/terminal-documentation",
    \\    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    \\    "profiles":
    \\    {
    \\        "list":
    \\        [
    \\            {
    \\                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    \\                "name": "Windows PowerShell",
    \\                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
    \\            },
    \\            {
    \\                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
    \\                "name": "Command Prompt",
    \\                "commandline": "%SystemRoot%\\System32\\cmd.exe"
    \\            },
    \\            {
    \\                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    \\                "name": "PowerShell",
    \\                "source": "Windows.Terminal.PowershellCore"
    \\            },
    \\            {
    \\                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    \\                "name": "Azure Cloud Shell",
    \\                "source": "Windows.Terminal.Azure"
    \\            },
    \\            {
    \\                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    \\                "name": "Ubuntu",
    \\                "source": "Windows.Terminal.Wsl"
    \\            },
    \\            {
    \\                "guid": "{d8b03b9c-49cf-58d7-83b7-7e19629d9cc0}",
    \\                "name": "archlinux",
    \\                "source": "Microsoft.WSL"
    \\            },
    \\            {
    \\                "guid": "{de27c996-0580-53f5-a62d-c2fee961383b}",
    \\                "name": "Developer Command Prompt for VS 2022",
    \\                "source": "Windows.Terminal.VisualStudio"
    \\            }
    \\        ]
    \\    }
    \\}
;

test "parse: dynamic default profile resolves and sorts first" {
    const profiles = try parse(std.testing.allocator, test_settings, test_env);
    defer free(std.testing.allocator, profiles);

    try std.testing.expect(profiles.len > 0);
    try std.testing.expect(profiles[0].is_default);
    try std.testing.expectEqualStrings("PowerShell", profiles[0].name);
    try std.testing.expectEqualStrings("pwsh.exe", profiles[0].command);
}

test "parse: %VAR% is expanded" {
    const profiles = try parse(std.testing.allocator, test_settings, test_env);
    defer free(std.testing.allocator, profiles);

    for (profiles) |profile| if (std.mem.eql(u8, profile.name, "Command Prompt")) {
        try std.testing.expectEqualStrings("C:\\Windows\\System32\\cmd.exe", profile.command);
        return;
    };
    return error.ProfileNotFound;
}

test "parse: wsl profiles launch by distro name" {
    const profiles = try parse(std.testing.allocator, test_settings, test_env);
    defer free(std.testing.allocator, profiles);

    var seen_ubuntu = false;
    var seen_arch = false;
    for (profiles) |profile| {
        if (std.mem.eql(u8, profile.name, "Ubuntu")) {
            try std.testing.expectEqualStrings("wsl.exe -d \"Ubuntu\"", profile.command);
            seen_ubuntu = true;
        }
        if (std.mem.eql(u8, profile.name, "archlinux")) {
            try std.testing.expectEqualStrings("wsl.exe -d \"archlinux\"", profile.command);
            seen_arch = true;
        }
    }
    try std.testing.expect(seen_ubuntu and seen_arch);
}

test "parse: unlaunchable sources are skipped" {
    const profiles = try parse(std.testing.allocator, test_settings, test_env);
    defer free(std.testing.allocator, profiles);

    for (profiles) |profile| {
        try std.testing.expect(!std.mem.eql(u8, profile.name, "Azure Cloud Shell"));
        try std.testing.expect(std.mem.indexOf(u8, profile.name, "Developer Command Prompt") == null);
    }
}

test "expandEnvVars: unknown and malformed are left alone" {
    const cases = [_][]const u8{ "%NOPE%\\x", "100%", "a %% b", "%" };
    for (cases) |case| {
        const out = try expandEnvVars(std.testing.allocator, case, test_env);
        defer std.testing.allocator.free(out);
        try std.testing.expectEqualStrings(case, out);
    }
}
