const Menu = @import("../Menu.zig");

pub const menu: Menu = .{ .label = "Menu", .items = &.{
    .{ .submenu = &file },
    .{ .submenu = &edit },
    .{ .submenu = &selection },
    .{ .submenu = &view },
    .{ .submenu = &go },
    .{ .submenu = &language },
    .{ .submenu = &terminal },
    .{ .submenu = &settings },
    .{ .submenu = &about },
} };

pub const file: Menu = .{ .label = "File", .items = &.{
    .{ .command = .{ .command = "create_new_file" } },
    .{ .command = .{ .command = "open_file" } },
    .{ .command = .{ .command = "find_file" } },
    .{ .command = .{ .command = "open_file_tree" } },
    .{ .command = .{ .command = "open_recent_project" } },
    .separator,
    .{ .command = .{ .command = "save_file" } },
    .{ .command = .{ .command = "save_as" } },
    .{ .command = .{ .command = "save_all" } },
    .{ .command = .{ .command = "save_file_with_formatting" } },
    .{ .command = .{ .command = "save_file_without_formatting" } },
    .{ .command = .{ .command = "force_save_file" } },
    .separator,
    .{ .command = .{ .command = "reload_file" } },
    .{ .command = .{ .command = "change_file_type" } },
    .{ .command = .{ .command = "toggle_eol_mode" } },
    .{ .command = .{ .command = "copy_file_name" } },
    .separator,
    .{ .command = .{ .command = "close_file" } },
    .{ .command = .{ .command = "close_file_without_saving" } },
    .{ .command = .{ .command = "restore_closed_tab" } },
    .separator,
    .{ .command = .{ .command = "save_session" } },
    .{ .command = .{ .command = "restart" } },
    .separator,
    .{ .command = .{ .command = "save_session_and_quit" } },
    .{ .command = .{ .command = "quit" } },
    .{ .command = .{ .command = "quit_without_saving" } },
} };

const edit: Menu = .{ .label = "Edit", .items = &.{
    .{ .command = .{ .command = "undo" } },
    .{ .command = .{ .command = "redo" } },
    .separator,
    .{ .command = .{ .command = "cut" } },
    .{ .command = .{ .command = "cut_internal_vim" } },
    .{ .command = .{ .command = "copy" } },
    .{ .command = .{ .command = "paste" } },
    .{ .command = .{ .command = "system_paste" } },
    .{ .command = .{ .command = "system_paste_primary" } },
    .{ .command = .{ .command = "clipboard_history" } },
    .separator,
    .{ .command = .{ .command = "find" } },
    .{ .command = .{ .command = "find_in_files" } },
    .{ .command = .{ .command = "find_word_at_cursor" } },
    .separator,
    .{ .command = .{ .command = "toggle_comment" } },
    .{ .command = .{ .command = "indent" } },
    .{ .command = .{ .command = "unindent" } },
    .{ .command = .{ .command = "reflow" } },
    .{ .submenu = &lines },
    .{ .submenu = &case },
} };

const lines: Menu = .{ .label = "Lines", .items = &.{
    .{ .command = .{ .command = "smart_insert_line_before" } },
    .{ .command = .{ .command = "smart_insert_line_after" } },
    .{ .command = .{ .command = "insert_line_before" } },
    .{ .command = .{ .command = "insert_line_after" } },
    .{ .command = .{ .command = "delete_line" } },
    .{ .command = .{ .command = "join_next_line" } },
    .separator,
    .{ .command = .{ .command = "dupe_up" } },
    .{ .command = .{ .command = "dupe_down" } },
    .{ .command = .{ .command = "pull_up" } },
    .{ .command = .{ .command = "pull_down" } },
} };

pub const case: Menu = .{ .label = "Case", .items = &.{
    .{ .command = .{ .command = "to_upper" } },
    .{ .command = .{ .command = "to_lower" } },
    .{ .command = .{ .command = "toggle_case" } },
    .{ .command = .{ .command = "switch_case" } },
} };

const selection: Menu = .{ .label = "Selection", .items = &.{
    .{ .command = .{ .command = "select_all" } },
    .{ .command = .{ .command = "select_line" } },
    .{ .command = .{ .command = "select_par" } },
    .{ .command = .{ .command = "selections_reverse" } },
    .separator,
    .{ .command = .{ .command = "expand_selection" } },
    .{ .command = .{ .command = "shrink_selection" } },
    .{ .command = .{ .command = "select_next_sibling" } },
    .{ .command = .{ .command = "select_prev_sibling" } },
    .separator,
    .{ .command = .{ .command = "add_cursor_up" } },
    .{ .command = .{ .command = "add_cursor_down" } },
    .{ .command = .{ .command = "add_cursor_next_match" } },
    .{ .command = .{ .command = "add_cursor_prev_match" } },
    .{ .command = .{ .command = "add_cursor_all_matches" } },
    .{ .command = .{ .command = "add_cursors_to_line_ends" } },
    .{ .command = .{ .command = "pop_cursor" } },
} };

const view: Menu = .{ .label = "View", .items = &.{
    .{ .command = .{ .command = "open_command_palette" } },
    .{ .command = .{ .command = "last_palette" } },
    .{ .command = .{ .command = "switch_buffers" } },
    .{ .command = .{ .command = "show_vcs_status" } },
    .separator,
    .{ .submenu = &splits },
    .{ .submenu = &tabs },
    .{ .submenu = &panel },
    .separator,
    .{ .command = .{ .command = "toggle_centered_view" } },
    .{ .command = .{ .command = "expand_centered_view", .on_activate = .keep_open } },
    .{ .command = .{ .command = "shrink_centered_view", .on_activate = .keep_open } },
    .separator,
    .{ .submenu = &display },
    .{ .submenu = &window },
    .{ .command = .{ .command = "toggle_menu" } },
    .{ .command = .{ .command = "toggle_keybind_hints" } },
} };

const splits: Menu = .{ .label = "Splits", .items = &.{
    .{ .command = .{ .command = "add_split" } },
    .{ .command = .{ .command = "close_split" } },
    .{ .command = .{ .command = "close_splits" } },
    .separator,
    .{ .command = .{ .command = "focus_next_split" } },
    .{ .command = .{ .command = "focus_prev_split" } },
} };

const tabs: Menu = .{ .label = "Tabs", .items = &.{
    .{ .command = .{ .command = "next_tab" } },
    .{ .command = .{ .command = "previous_tab" } },
    .{ .command = .{ .command = "move_tab_next" } },
    .{ .command = .{ .command = "move_tab_previous" } },
    .separator,
    .{ .command = .{ .command = "restore_closed_tab" } },
} };

const panel: Menu = .{ .label = "Panel", .items = &.{
    .{ .command = .{ .command = "toggle_panel" } },
    .{ .command = .{ .command = "toggle_maximize_panel" } },
    .{ .command = .{ .command = "focus_panel" } },
    .{ .command = .{ .command = "panel_unfocus" } },
    .{ .command = .{ .command = "grow_panel" } },
    .{ .command = .{ .command = "shrink_panel" } },
    .separator,
    .{ .command = .{ .command = "panel_tab_next" } },
    .{ .command = .{ .command = "panel_tab_prev" } },
    .{ .command = .{ .command = "panel_tab_close" } },
    .{ .command = .{ .command = "panel_split" } },
    .{ .command = .{ .command = "panel_move_tab_left" } },
    .{ .command = .{ .command = "panel_move_tab_right" } },
    .{ .command = .{ .command = "panel_focus_next_group" } },
    .{ .command = .{ .command = "panel_focus_prev_group" } },
    .separator,
    .{ .command = .{ .command = "panel_copy" } },
    .{ .command = .{ .command = "panel_clear" } },
    .separator,
    .{ .command = .{ .command = "show_logview" } },
    .{ .command = .{ .command = "show_diagnostics" } },
    .{ .command = .{ .command = "toggle_terminal_view" } },
    .{ .command = .{ .command = "show_filelist" } },
    .{ .command = .{ .command = "hide_filelist" } },
    .{ .command = .{ .command = "focus_filelist" } },
} };

const display: Menu = .{ .label = "Editor display", .items = &.{
    .{ .command = .{ .command = "toggle_whitespace_mode", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_highlight_columns", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_syntax_highlighting", .on_activate = .keep_open } },
    .separator,
    .{ .command = .{ .command = "gutter_mode_next", .on_activate = .keep_open } },
    .{ .command = .{ .command = "gutter_style_next", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_gutter_diffs", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_inline_diagnostics", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_inline_vcs_blame", .on_activate = .keep_open } },
    .separator,
    .{ .command = .{ .command = "scroll_view_center" } },
} };

const window: Menu = .{ .label = "Window", .items = &.{
    .{ .command = .{ .command = "toggle_fullscreen" } },
    .separator,
    .{ .command = .{ .command = "adjust_fontsize", .args = Menu.args(.{@as(f32, 1.0)}), .label = "Increase font size", .on_activate = .keep_open } },
    .{ .command = .{ .command = "adjust_fontsize", .args = Menu.args(.{@as(f32, -1.0)}), .label = "Decrease font size", .on_activate = .keep_open } },
    .{ .command = .{ .command = "reset_fontsize", .on_activate = .keep_open } },
    .separator,
    .{ .command = .{ .command = "adjust_background_opacity", .args = Menu.args(.{@as(f32, 0.05)}), .label = "Increase window opacity", .on_activate = .keep_open } },
    .{ .command = .{ .command = "adjust_background_opacity", .args = Menu.args(.{@as(f32, -0.05)}), .label = "Decrease window opacity", .on_activate = .keep_open } },
    .{ .command = .{ .command = "reset_background_opacity", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_ignore_theme_alpha", .on_activate = .keep_open } },
} };

pub const go: Menu = .{ .label = "Go", .items = &.{
    .{ .command = .{ .command = "jump_back" } },
    .{ .command = .{ .command = "jump_forward" } },
    .separator,
    .{ .command = .{ .command = "goto" } },
    .{ .command = .{ .command = "goto_offset" } },
    .{ .command = .{ .command = "goto_word" } },
    .{ .command = .{ .command = "goto_bracket" } },
    .{ .command = .{ .command = "move_buffer_begin" } },
    .{ .command = .{ .command = "move_buffer_end" } },
    .separator,
    .{ .command = .{ .command = "goto_next_match" } },
    .{ .command = .{ .command = "goto_prev_match" } },
    .{ .command = .{ .command = "goto_next_change" } },
    .{ .command = .{ .command = "goto_prev_change" } },
    .{ .command = .{ .command = "goto_next_diagnostic" } },
    .{ .command = .{ .command = "goto_prev_diagnostic" } },
    .{ .command = .{ .command = "goto_next_file_or_diagnostic" } },
    .{ .command = .{ .command = "goto_prev_file_or_diagnostic" } },
    .separator,
    .{ .command = .{ .command = "open_previous_file" } },
    .{ .command = .{ .command = "open_most_recent_file" } },
    .{ .command = .{ .command = "open_file_links" } },
} };

pub const language: Menu = .{ .label = "Language", .items = &.{
    .{ .command = .{ .command = "goto_definition" } },
    .{ .command = .{ .command = "goto_declaration" } },
    .{ .command = .{ .command = "goto_implementation" } },
    .{ .command = .{ .command = "goto_type_definition" } },
    .{ .command = .{ .command = "references" } },
    .{ .command = .{ .command = "show_symbols" } },
    .separator,
    .{ .command = .{ .command = "hover" } },
    .{ .command = .{ .command = "completion" } },
    .{ .command = .{ .command = "highlight_references" } },
    .{ .command = .{ .command = "rename_symbol" } },
    .{ .command = .{ .command = "format" } },
    .separator,
    .{ .command = .{ .command = "show_diagnostics" } },
    .{ .command = .{ .command = "toggle_inline_diagnostics", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_auto_highlight_references", .on_activate = .keep_open } },
    .{ .command = .{ .command = "toggle_auto_hover" } },
    .{ .command = .{ .command = "toggle_format_on_save" } },
    .separator,
    .{ .command = .{ .command = "restart_language_server" } },
} };

const terminal: Menu = .{ .label = "Terminal", .items = &.{
    .{ .command = .{ .command = "open_terminal" } },
    .{ .command = .{ .command = "terminal_new" } },
    .{ .command = .{ .command = "toggle_terminal_view" } },
    .{ .command = .{ .command = "switch_terminals" } },
    .{ .command = .{ .command = "terminal_next_vt" } },
    .{ .command = .{ .command = "terminal_previous_vt" } },
    .{ .command = .{ .command = "close_terminal" } },
    .separator,
    .{ .command = .{ .command = "send_selection_to_terminal" } },
    .{ .command = .{ .command = "terminal_copy_selection" } },
    .{ .command = .{ .command = "terminal_open_file_links" } },
    .{ .command = .{ .command = "terminal_open_last_command_output" } },
    .{ .command = .{ .command = "terminal_open_scrollback_buffer" } },
    .{ .command = .{ .command = "terminal_scroll_previous_command" } },
    .{ .command = .{ .command = "terminal_scroll_next_command" } },
    .{ .command = .{ .command = "terminal_kill" } },
    .separator,
    .{ .command = .{ .command = "run_task" } },
    .{ .command = .{ .command = "add_task" } },
} };

const settings: Menu = .{ .label = "Settings", .items = &.{
    .{ .submenu = &theme },
    .{ .command = .{ .command = "change_fontface" } },
    .{ .command = .{ .command = "reset_fontface" } },
    .{ .command = .{ .command = "toggle_input_mode" } },
    .separator,
    .{ .command = .{ .command = "set_tab_width" } },
    .{ .command = .{ .command = "set_buffer_tab_width" } },
    .{ .command = .{ .command = "set_session_tab_width" } },
    .separator,
    .{ .submenu = &completion },
    .{ .command = .{ .command = "toggle_hover_info_mode" } },
    .{ .command = .{ .command = "toggle_auto_find" } },
    .{ .command = .{ .command = "toggle_auto_save" } },
    .{ .command = .{ .command = "toggle_format_on_save" } },
    .separator,
    .{ .command = .{ .command = "open_config" } },
    .{ .command = .{ .command = "open_gui_config" } },
    .{ .command = .{ .command = "open_keybind_config" } },
    .{ .command = .{ .command = "open_tabs_style_config" } },
    .{ .command = .{ .command = "open_home_style_config" } },
    .{ .command = .{ .command = "open_lsp_config_global" } },
    .{ .command = .{ .command = "open_lsp_config_project" } },
    .{ .command = .{ .command = "open_file_type_config" } },
} };

const theme: Menu = .{ .label = "Theme", .items = &.{
    .{ .command = .{ .command = "change_theme" } },
    .{ .command = .{ .command = "toggle_color_scheme", .on_activate = .keep_open } },
    .{ .command = .{ .command = "open_custom_theme" } },
    .separator,
    .{ .command = .{ .command = "theme_next", .on_activate = .keep_open } },
    .{ .command = .{ .command = "theme_prev", .on_activate = .keep_open } },
} };

const completion: Menu = .{ .label = "Completion", .items = &.{
    .{ .command = .{ .command = "toggle_completion_trigger" } },
    .{ .command = .{ .command = "toggle_completion_style" } },
    .{ .command = .{ .command = "toggle_completion_insert_mode" } },
    .{ .command = .{ .command = "toggle_completion_info" } },
} };

const about: Menu = .{ .label = "About", .items = &.{
    .{ .command = .{ .command = "open_help" } },
    .{ .command = .{ .command = "insert_command_name" } },
    .{ .command = .{ .command = "open_version_info" } },
    .separator,
    .{ .submenu = &debug },
} };

const debug: Menu = .{ .label = "Debug", .items = &.{
    .{ .command = .{ .command = "toggle_inspector_view" } },
    .{ .command = .{ .command = "toggle_inputview" } },
    .{ .command = .{ .command = "toggle_keybindview" } },
    .{ .command = .{ .command = "toggle_command_logging" } },
    .{ .command = .{ .command = "toggle_syntax_timing" } },
    .separator,
    .{ .command = .{ .command = "dump_widget_tree" } },
    .{ .command = .{ .command = "dump_current_line" } },
    .{ .command = .{ .command = "dump_current_line_tree" } },
    .{ .command = .{ .command = "dump_document_tree" } },
    .{ .command = .{ .command = "open_font_test_text" } },
    .{ .command = .{ .command = "toggle_symbol_rasterizer" } },
    .{ .command = .{ .command = "save_screenshot" } },
    .{ .command = .{ .command = "force_crash_dump" } },
} };
