#!/bin/sh
set -e

BUILDER="$(cd "$(dirname "$0")" && pwd)"
BASEDIR="$(cd "$(dirname "$0")/../.." && pwd)"
APPNAME="$(basename "$BASEDIR")"

IMAGE="$APPNAME-builder-zig-0.17-dev"
NAME="$APPNAME-builder-zig-0.17-dev"

cd "$BASEDIR"

mkdir -p "$BASEDIR/.zig-cache/builder/local"
mkdir -p "$BASEDIR/.zig-cache/builder/global"
mkdir -p "$BASEDIR/zig-pkg/builder"

docker pull archlinux:latest

docker build \
    --build-context zig=../zig \
    -t "$IMAGE" \
    "$BUILDER"
docker run --rm -ti \
    --hostname "$NAME" \
    -u 1000:1000 \
    -v "$BASEDIR:/src/flow" \
    -v "$BASEDIR/.zig-cache/builder/local:/src/flow/.zig-cache" \
    -v "$BASEDIR/.zig-cache/builder/global:/home/builder/.cache/zig" \
    -v "$BASEDIR/zig-pkg/builder:/src/flow/zig-pkg" \
    "$IMAGE" \
    zig build "$@"
