#!/bin/sh
set -e

BUILDER="$(cd "$(dirname "$0")" && pwd)"
BASEDIR="$(cd "$(dirname "$0")/../.." && pwd)"
APPNAME="$(basename "$BASEDIR")"

IMAGE="$APPNAME-builder"
NAME="$APPNAME-builder"

cd "$BASEDIR"

docker pull archlinux:latest

docker build -t "$IMAGE" "$BUILDER"
docker run --rm -ti --hostname "$NAME" -u 1000:1000 -v "$BASEDIR:/src/flow" "$IMAGE" zig build "$@"
