name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          repository: neurocyte/flow
          ref: master

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0  # Ensuring the required version is installed

      - name: Build Flow
        run: zig build -Doptimize=ReleaseSafe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Fixed: Using v4 instead of v3
        with:
          name: flow-nightly
          path: zig-out/bin/flow

      - name: Create Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_id }}
          name: Nightly Build ${{ github.run_id }}
          body: "Automated nightly build of Flow."
          draft: false
          prerelease: true
          files: zig-out/bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
