name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/neurocyte/flow.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout master  # Use `master` instead of `main`
          git merge upstream/master --no-edit
          git push origin master
